### PR TITLE
ver 0.2 updated map & 4 terrain units

### PR DESCRIPTION
**Pull request by TheDog-GH**

### CODE REVIEW

**Comment by TheDog-GH** [comment]
updated map & added 4 terrain units
Please update yaml version to 2

**Review by beelee1 — APPROVED** [review]
Idk if this will work but lets try it. Hmm ... did Roger end up making the map repo then ? If so, maybe he can give you write access so you can do updates on your own.

Anyway we'll try this. Here's what it looks like. Never done it before.

Screenshot from 2022-08-29 05-25-04

**Comment by beelee1** [comment]
@TheDog-GH ah yea, I don't have write access either

**Comment by TheDog-GH** [comment]
Thanks for trying.
I think a few more of us should be map admins, so we dont keep bothering Roger, as it looks like he is a team of 1.

**Comment by beelee1** [comment]
@TheDog-GH yea i still don't understand the process entirely. Roi is a developer and doesn't have access or asvitkine. I think Dan and maybe Roger is the only one that i know of.

There should ( and I think there is ) be a way you can setup your own repo from the start. What is needed, is for Dan to take the time and make a step by step guide like Frostion did about how to do it. Dropping hints here and there for us to try and figure it out, is confusing and inefficient.

He's been busy and my impression, not particularly interested in doing it. Therefore, we will continue to struggle :)

**Comment by TheDog-GH** [comment]
I also dont fully understand the process either, but I would like to be made a map admin, I will do a tutorial for 
- initial load
- 2nd and subsequent loads
- 
Then Roger and I and maybe you(if you wanted) could cover the map uploads.

Also I will need access for doing the map tags for ver 2.6

**Comment by beelee1** [comment]
yea so Dan gave me the power to upload but not Roger. Gave Roger the map admin but not Roi. You see where this is going :)

**Comment by TheDog-GH** [comment]
Beelee would you want to be a map admin, like Roger?

**Comment by beelee1** [comment]
oh idk I think one can add there map without one right now. That's why you don't need to change ownership anymore. Then you should have write access to it. I'm just not sure of how to do it.

**Comment by RogerCooper** [comment]
I also don't know how to make this work.

**Comment by RogerCooper** [comment]
I think I merged it onto Github.

**Comment by TheDog-GH** [comment]
Beelee would you want to be a map admin, like Roger?

**Pull request merged**
